basePath: /
definitions:
  models.Song:
    description: Модель песни
    properties:
      group:
        description: Название группы
        type: string
      song:
        description: Название песни
        type: string
    type: object
  models.SongDetails:
    description: Модель дополнительных данных песни
    properties:
      link:
        description: Ссылка на песню
        example: ""
        type: string
      releaseDate:
        description: Дата выхода песни
        example: ""
        type: string
      text:
        description: Текст песни
        example: ""
        type: string
    type: object
  models.SongWithDetails:
    description: Модель песни c дополнительными данными песни
    properties:
      SongDetails:
        $ref: '#/definitions/models.SongDetails'
      group:
        example: ""
        type: string
      song:
        example: ""
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API для управления библиотекой песен.
  version: "1.0"
paths:
  /songs:
    get:
      consumes:
      - application/json
      description: Получить список всех песен
      parameters:
      - description: Фильтр по группе
        in: query
        name: group
        type: string
      - description: Фильтр по названию песни
        in: query
        name: song
        type: string
      - description: Фильтр по ссылке
        in: query
        name: link
        type: string
      - description: Фильтр по тексту или фрагменту тектса
        in: query
        name: text
        type: string
      - description: Поле для сортировки asc для возрастания и desc для убывания
        in: query
        name: sort
        type: string
      - default: 1
        description: Номер страницы(пагинация)
        in: query
        name: page
        type: integer
      - default: 10
        description: Лимит записей на странице
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Song'
            type: array
        "400":
          description: Неверный формат параметров запроса
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получить все песни
      tags:
      - songs
    post:
      consumes:
      - application/json
      description: Добавить новую песню
      parameters:
      - description: Данные песни
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/models.Song'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.Song'
        "400":
          description: Песня уже добавлена
          schema:
            type: string
        "500":
          description: Ошибка при получении данных от внешнего API
          schema:
            type: string
      summary: Добавить песню
      tags:
      - songs
  /songs/{id}:
    delete:
      consumes:
      - application/json
      description: Удалить песню по её ID
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Песня успешно удалена
          schema:
            type: string
        "404":
          description: Песня не найдена
          schema:
            type: string
        "500":
          description: Ошибка при удалении песни
          schema:
            type: string
      summary: Удалить песню
      tags:
      - songs
    put:
      consumes:
      - application/json
      description: Редактировать песню по её ID
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      - description: Данные песни
        in: body
        name: song
        schema:
          $ref: '#/definitions/models.SongWithDetails'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.Song'
        "400":
          description: 'Неверный формат даты. Ожидаемый формат: DD.MM.YYYY'
          schema:
            type: string
        "404":
          description: Детали песни не найдены
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Редактировать песню
      tags:
      - songs
  /songs/{id}/text:
    get:
      consumes:
      - application/json
      description: Получить текст песни по её ID
      parameters:
      - description: ID песни
        in: path
        name: id
        required: true
        type: integer
      - default: 1
        description: Номер страницы(пагинация)
        in: query
        name: page
        type: integer
      - default: 5
        description: Лимит куплетов на странице
        in: query
        name: limit
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Текст песни
          schema:
            type: string
        "400":
          description: Неверный формат параметров запроса
          schema:
            type: string
        "404":
          description: Текст песни отсутствует
          schema:
            type: string
        "500":
          description: Внутренняя ошибка сервера
          schema:
            type: string
      summary: Получить текст песни
      tags:
      - songs
swagger: "2.0"
